[workspace]
resolver = "3"
members = [
  "crates/visitors",
  "standalone",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.92.0"
license-file = "LICENSE"
publish = false

[workspace.dependencies]
actix-web = "4.12.1"
base64 = "0.22.1"
rand = "0.9.2"
tokio = "1.48.0"
